import {FormEvent,useEffect,useMemo,useRef,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useSearchParams} from 'react-router-dom';
import Plot from 'react-plotly.js';
import {Activity,ArrowRight,ArrowUp,BarChart3,Check,ChevronRight,Database,FileSpreadsheet,FileUp,Lightbulb,Loader2,Plus,Search,ShieldCheck,Sparkles,Table2,TerminalSquare,X} from 'lucide-react';
import {AnalystResult,api,Dataset} from '../api';

type Tab='overview'|'data'|'charts'|'insights'|'sql'|'activity';
type Message={question:string;result:AnalystResult};
const tabs:[Tab,string,any][]=[['overview','Overview',Database],['data','Data',Table2],['charts','Charts',BarChart3],['insights','Insights',Lightbulb],['sql','SQL',TerminalSquare],['activity','Activity',Activity]];
const fmt=(value:any)=>value==null?'—':typeof value==='number'?value.toLocaleString(undefined,{maximumFractionDigits:2}):String(value);
const words=(value:string)=>value.replaceAll('_',' ');
const friendlyError=(error:unknown)=>{const message=error instanceof Error?error.message:String(error);if(/nan|out of range float|json compliant/i.test(message))return 'The analysis contained an empty numeric value that could not be displayed. DataPilot has protected the result; please run the question again.';return `${message}. Try rephrasing the question or choose another dataset.`};

export default function Analyst(){
  const [params]=useSearchParams(); const qc=useQueryClient();
  const [query,setQuery]=useState(''); const [pendingQuestion,setPendingQuestion]=useState(''); const [session,setSession]=useState<string>(); const [selected,setSelected]=useState(params.get('dataset')||'');
  const [messages,setMessages]=useState<Message[]>([]); const [tab,setTab]=useState<Tab>('overview'); const [sourceSearch,setSourceSearch]=useState(''); const [progressIndex,setProgressIndex]=useState(0);
  const [uploading,setUploading]=useState(false); const [uploadError,setUploadError]=useState(''); const fileInput=useRef<HTMLInputElement>(null); const conversationEnd=useRef<HTMLDivElement>(null);
  const datasets=useQuery({queryKey:['datasets'],queryFn:()=>api<Dataset[]>('/api/datasets'),refetchInterval:query=>query.state.data?.length?false:5000});
  const health=useQuery({queryKey:['health'],queryFn:()=>api<{database:string;storage:string}>('/api/system/health'),refetchInterval:15000,retry:1});
  useEffect(()=>{if(datasets.data?.length&&!datasets.data.some(item=>item.id===selected)){setSelected(datasets.data[0].id);setSession(undefined);setMessages([])}},[datasets.data,selected]);
  const dataset=datasets.data?.find(item=>item.id===selected);
  const detail=useQuery({queryKey:['dataset-detail',selected],queryFn:()=>api<any>(`/api/datasets/${selected}`),enabled:!!selected});
  const profile=useQuery({queryKey:['dataset-profile',selected],queryFn:()=>api<any>(`/api/datasets/${selected}/profile`),enabled:!!selected});
  const ask=useMutation({mutationFn:async(question:string)=>{const started=Date.now();const result=await api<AnalystResult>('/api/analyst/query',{method:'POST',body:JSON.stringify({query:question,session_id:session,dataset:selected||undefined})});const remaining=1800-(Date.now()-started);if(remaining>0)await new Promise(resolve=>setTimeout(resolve,remaining));return result},onSuccess:(result,question)=>{setSession(result.session_id);setMessages(old=>[...old,{question,result}]);setPendingQuestion('');setTab('insights')},onError:()=>setPendingQuestion('')});
  const latest=messages.at(-1)?.result;
  const progressSteps=useMemo(()=>{
    const q=pendingQuestion.toLowerCase();
    if(q.includes('predict')||q.includes('model')||q.includes('train'))return ['Understanding the prediction goal','Inspecting fields and data quality','Preparing data without leakage','Training suitable models','Comparing measured results','Preparing the analysis summary'];
    if(q.includes('clean')||q.includes('quality'))return ['Understanding the data-quality request','Profiling every field','Identifying issues and affected rows','Preparing safe recommendations','Validating the proposed plan','Preparing the analysis summary'];
    return ['Understanding your question','Reading the selected dataset','Choosing the right analysis','Running the calculations','Validating the findings','Preparing the analysis summary'];
  },[pendingQuestion]);
  useEffect(()=>{if(!ask.isPending){setProgressIndex(0);return}const timer=setInterval(()=>setProgressIndex(value=>Math.min(value+1,progressSteps.length-1)),900);return()=>clearInterval(timer)},[ask.isPending,progressSteps.length]);
  const resume=useMutation({mutationFn:(decision:string)=>api<AnalystResult>('/api/analyst/continue',{method:'POST',body:JSON.stringify({session_id:latest!.session_id,run_id:latest!.run_id,decision})}),onSuccess:result=>{setMessages(old=>old.map((message,index)=>index===old.length-1?{...message,result}:message));const active=result.context.dataset_id;if(active){setSelected(active);qc.invalidateQueries({queryKey:['datasets']});qc.invalidateQueries({queryKey:['dataset-detail',active]});qc.invalidateQueries({queryKey:['dataset-profile',active]})}setTab('insights')}});
  useEffect(()=>{conversationEnd.current?.scrollIntoView({behavior:'smooth'})},[messages,ask.isPending]);
  const run=(question:string)=>{const clean=question.trim();if(clean&&selected&&!ask.isPending){setPendingQuestion(clean);ask.mutate(clean);setQuery('')}};
  const submit=(event?:FormEvent)=>{event?.preventDefault();run(query)};
  const selectDataset=(id:string)=>{setSelected(id);setSession(undefined);setMessages([]);setTab('overview')};
  const upload=async(file?:File)=>{if(!file)return;setUploading(true);setUploadError('');try{const response=await fetch(`/api/datasets/upload?name=${encodeURIComponent(file.name.replace(/\.csv$/i,''))}`,{method:'POST',headers:{'Content-Type':'text/csv'},body:file});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Upload failed');await qc.invalidateQueries({queryKey:['datasets']});selectDataset(data.id)}catch(error:any){setUploadError(error.message)}finally{setUploading(false);if(fileInput.current)fileInput.current.value=''}};
  const filtered=datasets.data?.filter(item=>item.display_name.toLowerCase().includes(sourceSearch.toLowerCase()))||[];
  const chart=latest?.artifacts?.at(-1)?.figure;
  const sqlSteps=latest?.steps?.filter(step=>step.result?.query)||[];
  const starters=dataset?[`Analyze ${dataset.display_name} and show the most important findings.`,`What groups or segments stand out in ${dataset.display_name}?`,`Does this data have quality problems?`,`Create a useful chart for management.`]:[];
  return <div className="-m-6 flex h-[calc(100vh-4rem)] min-h-[680px] overflow-hidden bg-white">
    <aside className="flex w-[250px] shrink-0 flex-col border-r border-slate-200 bg-[#f8fafc]">
      <div className="border-b border-slate-200 p-4"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold text-slate-900">Data sources</div><div className="mt-0.5 text-[11px] text-slate-500">Choose what to analyze</div></div><button title="Upload CSV" onClick={()=>fileInput.current?.click()} className="grid h-8 w-8 place-items-center rounded-md border border-slate-200 bg-white text-slate-600 hover:border-teal-400 hover:text-teal-700"><Plus size={16}/></button><input ref={fileInput} type="file" accept=".csv,text/csv" className="hidden" onChange={event=>upload(event.target.files?.[0])}/></div><div className="relative mt-3"><Search size={14} className="absolute left-3 top-2.5 text-slate-400"/><input value={sourceSearch} onChange={e=>setSourceSearch(e.target.value)} placeholder="Find a dataset" className="w-full rounded-md border border-slate-200 bg-white py-2 pl-8 pr-3 text-xs outline-none focus:border-teal-500"/></div></div>
      <div className="scrollbar flex-1 overflow-y-auto p-2"><div className="px-2 pb-2 pt-1 text-[10px] font-semibold uppercase tracking-wider text-slate-400">{health.data?.storage||'Checking data connection'} · {health.data?.database==='healthy'?'connected':'unavailable'}</div>{health.data?.storage==='Local recovery database'&&<div className="mx-2 mb-3 rounded-md border border-amber-200 bg-amber-50 p-2 text-[11px] leading-4 text-amber-800">Showing locally recovered public datasets. PostgreSQL history and versions will return when Docker is repaired.</div>}{datasets.isError&&<div className="mx-2 rounded-md border border-red-200 bg-red-50 p-3 text-xs text-red-700">Datasets could not be loaded. Check Connections for the current status.</div>}{filtered.map(item=><button key={item.id} onClick={()=>selectDataset(item.id)} className={`mb-1 w-full rounded-lg border p-3 text-left transition ${selected===item.id?'border-teal-200 bg-white shadow-sm':'border-transparent hover:bg-white'}`}><div className="flex gap-2.5"><span className={`mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-md ${selected===item.id?'bg-teal-50 text-teal-700':'bg-slate-100 text-slate-500'}`}><Database size={14}/></span><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold text-slate-800">{item.display_name}</div><div className="mt-1 text-[10px] text-slate-400">{fmt(item.rows)} rows · {item.columns} columns</div><div className="mt-1.5 flex items-center gap-1 text-[10px] text-emerald-600"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/>Ready</div></div>{selected===item.id&&<ChevronRight size={14} className="mt-1 text-teal-600"/>}</div></button>)}</div>
      <div className="border-t border-slate-200 p-3"><button disabled={uploading} onClick={()=>fileInput.current?.click()} className="flex w-full items-center justify-center gap-2 rounded-md border border-slate-300 bg-white py-2 text-xs font-semibold text-slate-700 hover:border-teal-500 disabled:opacity-50">{uploading?<Loader2 size={14} className="animate-spin"/>:<FileUp size={14}/>}Upload CSV</button>{uploadError&&<div className="mt-2 rounded bg-red-50 p-2 text-[10px] text-red-700">{uploadError}</div>}<div className="mt-2 text-center text-[10px] text-slate-400">Uploads are stored as a new raw dataset</div></div>
    </aside>

    <section className="flex min-w-[420px] flex-1 flex-col bg-white">
      <div className="flex h-[68px] items-center justify-between border-b border-slate-200 px-5"><div className="min-w-0"><div className="flex items-center gap-2"><h1 className="truncate text-sm font-semibold text-slate-900">AI Data Analyst</h1><span className="rounded bg-teal-50 px-2 py-0.5 text-[10px] font-semibold text-teal-700">LIVE</span></div><div className="mt-1 flex items-center gap-1.5 text-[11px] text-slate-500"><Database size={11}/>{dataset?.display_name||'Select a dataset'}{dataset&&<><span>·</span><span>{fmt(dataset.rows)} rows</span></>}</div></div><button onClick={()=>{setMessages([]);setSession(undefined);setTab('overview')}} className="rounded-md border border-slate-200 px-3 py-1.5 text-xs text-slate-600 hover:bg-slate-50">New analysis</button></div>
      <div className="scrollbar flex-1 overflow-y-auto px-6 py-5">
        {!messages.length&&!ask.isPending&&<div className="mx-auto flex h-full max-w-2xl flex-col justify-center py-8"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#153c3f] text-teal-200"><Sparkles size={20}/></div><h2 className="mt-5 text-2xl font-semibold tracking-tight text-slate-900">What would you like to understand?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Ask a business question. DataPilot will inspect the selected data, run the calculations, and show the evidence.</p><div className="mt-6 grid gap-2">{starters.map((question,index)=><button key={question} onClick={()=>run(question)} className="group flex items-center gap-3 rounded-lg border border-slate-200 px-4 py-3 text-left text-sm text-slate-600 hover:border-teal-300 hover:bg-teal-50/40"><span className="grid h-7 w-7 place-items-center rounded-md bg-slate-100 text-xs font-semibold text-slate-500 group-hover:bg-white">{index+1}</span><span className="flex-1">{question}</span><ArrowRight size={14} className="text-slate-300 group-hover:text-teal-600"/></button>)}</div></div>}
        {messages.map((message,index)=><div key={message.result.run_id||index} className="mx-auto mb-7 max-w-3xl"><div className="ml-auto max-w-[82%] rounded-2xl rounded-br-md bg-[#153c3f] px-4 py-3 text-sm leading-6 text-white">{message.question}</div><div className="mt-4 flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-teal-50 text-teal-700"><Sparkles size={15}/></span><div className="min-w-0 flex-1"><div className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-wider text-teal-700">Answer <span className="flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-0.5 normal-case tracking-normal text-emerald-700"><Check size={10}/>{message.result.plan?.[0]?.tool==='clarify_question'?'Needs a clearer question':'Computed from data'}</span></div><AnswerView result={message.result}/>{message.result.errors?.length>0&&<div className="mt-3 rounded-md bg-red-50 p-3 text-xs text-red-700">{message.result.errors.map((error:any)=>error.message).join(' · ')}</div>}</div></div></div>)}
        {ask.isPending&&<div className="mx-auto max-w-3xl"><div className="ml-auto max-w-[82%] rounded-2xl rounded-br-md bg-[#153c3f] px-4 py-3 text-sm leading-6 text-white">{pendingQuestion}</div><div className="mt-4 flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-teal-50 text-teal-700"><Loader2 size={15} className="animate-spin"/></span><div className="flex-1"><div className="text-sm font-semibold text-slate-800">Analysis in progress</div><div className="mt-1 text-xs text-slate-400">Working through the question step by step</div><div className="mt-4 overflow-hidden rounded-lg border border-slate-200 bg-white">{progressSteps.map((step,index)=><div key={step} className={`flex items-center gap-3 border-b border-slate-100 px-4 py-3 last:border-0 ${index===progressIndex?'bg-teal-50/60':''}`}><span className={`grid h-5 w-5 shrink-0 place-items-center rounded-full ${index<progressIndex?'bg-emerald-100 text-emerald-700':index===progressIndex?'bg-teal-600 text-white':'bg-slate-100 text-slate-300'}`}>{index<progressIndex?<Check size={11}/>:index===progressIndex?<Loader2 size={11} className="animate-spin"/>:<span className="h-1.5 w-1.5 rounded-full bg-current"/>}</span><div className={`text-xs ${index<=progressIndex?'font-medium text-slate-700':'text-slate-400'}`}>{step}</div>{index===progressIndex&&<span className="ml-auto text-[10px] font-medium text-teal-700">Working…</span>}</div>)}</div></div></div></div>}
        {ask.isError&&<div className="mx-auto max-w-3xl rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{friendlyError(ask.error)}</div>}
        {latest?.pending_approval&&<Approval result={latest} pending={resume.isPending} decide={decision=>resume.mutate(decision)}/>}<div ref={conversationEnd}/>
      </div>
      <form onSubmit={submit} className="border-t border-slate-200 bg-white p-4"><div className="mx-auto max-w-3xl rounded-xl border border-slate-300 bg-white p-2 shadow-sm focus-within:border-teal-500 focus-within:ring-2 focus-within:ring-teal-100"><textarea value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}}} rows={2} placeholder={selected?'Ask anything about the selected data…':'Select a dataset first'} disabled={!selected} className="block min-h-[54px] w-full resize-none px-2 py-1 text-sm outline-none disabled:bg-white"/><div className="flex items-center justify-between px-1"><span className="text-[10px] text-slate-400">Enter to analyze · Shift + Enter for a new line</span><button aria-label="Analyze question" disabled={!query.trim()||!selected||ask.isPending} className="grid h-8 w-8 place-items-center rounded-lg bg-[#153c3f] text-white disabled:cursor-not-allowed disabled:opacity-30"><ArrowUp size={15}/></button></div></div></form>
    </section>

    <aside className="flex w-[390px] shrink-0 flex-col border-l border-slate-200 bg-[#f8fafc]">
      <div className="border-b border-slate-200 bg-white px-4"><div className="flex h-[68px] items-end gap-0 overflow-x-auto">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} title={label} className={`flex h-11 min-w-0 flex-1 items-center justify-center gap-1 border-b-2 px-1 text-[10px] font-medium ${tab===id?'border-teal-600 text-teal-700':'border-transparent text-slate-400 hover:text-slate-700'}`}><Icon size={13}/><span>{label}</span></button>)}</div></div>
      <div className="scrollbar flex-1 overflow-y-auto p-4"><WorkspaceTab tab={tab} dataset={dataset} detail={detail.data} profile={profile.data} loading={detail.isFetching||profile.isFetching} result={latest} question={messages.at(-1)?.question||pendingQuestion} chart={chart} sqlSteps={sqlSteps}/></div>
    </aside>
  </div>
}

function WorkspaceTab({tab,dataset,detail,profile,loading,result,question,chart,sqlSteps}:{tab:Tab;dataset?:Dataset;detail:any;profile:any;loading:boolean;result?:AnalystResult;question?:string;chart:any;sqlSteps:any[]}){
  if(!dataset)return <EmptyState icon={<Database/>} title="Select a data source" text="Choose a dataset on the left to begin."/>;
  if(loading&&!profile)return <EmptyState icon={<Loader2 className="animate-spin"/>} title="Reading the data" text="Preparing the dataset overview."/>;
  if(tab==='overview')return <div className="space-y-4"><SectionTitle title={dataset.display_name} text={dataset.description}/><div className="grid grid-cols-2 gap-2"><MiniStat label="Rows" value={fmt(profile?.shape?.rows||dataset.rows)}/><MiniStat label="Columns" value={profile?.shape?.columns||dataset.columns}/><MiniStat label="Missing" value={`${profile?.missing_pct??0}%`}/><MiniStat label="Duplicates" value={fmt(profile?.duplicate_rows??0)}/></div><Box title="Data readiness"><div className="flex items-start gap-2"><ShieldCheck size={16} className={profile?.issues?.length?'text-amber-600':'text-emerald-600'}/><div className="text-xs leading-5 text-slate-600">{profile?.issues?.length?`${profile.issues.length} items are worth reviewing before important decisions.`:'No major quality problems were detected.'}</div></div></Box><Box title="Purpose"><p className="text-xs leading-5 text-slate-600">Use this dataset for {dataset.tasks.map(words).join(', ')}.{dataset.targets.length?` The main outcome is ${dataset.targets.map(words).join(', ')}.`:''}</p></Box></div>;
  if(tab==='data')return <div><SectionTitle title="Data preview" text="A small sample from the selected source."/><div className="mt-4 overflow-auto rounded-lg border border-slate-200 bg-white"><table className="whitespace-nowrap"><thead><tr>{detail?.schema?.columns?.slice(0,6).map((column:any)=><th key={column.name}>{words(column.name)}</th>)}</tr></thead><tbody>{detail?.sample?.slice(0,8).map((row:any,index:number)=><tr key={index}>{detail.schema.columns.slice(0,6).map((column:any)=><td key={column.name}>{fmt(row[column.name])}</td>)}</tr>)}</tbody></table></div><div className="mt-4 space-y-2"><div className="text-xs font-semibold text-slate-700">Schema</div>{profile?.columns?.slice(0,12).map((column:any)=><div key={column.name} className="flex items-center justify-between rounded-md border border-slate-200 bg-white px-3 py-2"><div><div className="text-xs font-medium text-slate-700">{words(column.name)}</div><div className="text-[10px] text-slate-400">{column.dtype}</div></div><div className="text-right text-[10px] text-slate-400">{column.missing_pct}% missing<br/>{fmt(column.unique)} unique</div></div>)}</div></div>;
  if(tab==='charts')return chart?<div><SectionTitle title={chart.layout?.title?.text||'Analysis chart'} text="Interactive chart generated from the selected data."/><div className="mt-3 rounded-lg border border-slate-200 bg-white"><Plot data={chart.data} layout={{...chart.layout,paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{color:'#475569',size:10},autosize:true,margin:{t:50,r:15,b:55,l:55}}} config={{displaylogo:false,responsive:true}} useResizeHandler style={{width:'100%',height:390}}/></div></div>:<EmptyState icon={<BarChart3/>} title="No chart yet" text="Ask for a comparison, trend, distribution, or management chart."/>;
  if(tab==='insights')return result?.answer?<div><SectionTitle title="At a glance" text="The answer is in the middle. This panel shows its main point and what was checked."/><div className="mt-4 rounded-lg border border-slate-200 bg-white p-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Question asked</div><div className="mt-1 text-sm font-medium leading-6 text-slate-800">{question}</div></div><div className="mt-3 rounded-lg border border-teal-100 bg-teal-50/40 p-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-teal-700">Main finding</div><div className="mt-2 text-sm font-semibold leading-6 text-slate-800">{result.answer_structure?.headline||result.answer.split('\n')[0]}</div></div>{result.answer_structure&&result.answer_structure.metrics.length>0&&<div className="mt-3 grid grid-cols-2 gap-2">{result.answer_structure.metrics.map(metric=><MiniStat key={metric.label} label={metric.label} value={metric.value}/>)}</div>}<Box title="How this was checked"><ul className="space-y-2">{result.steps?.filter(step=>step.status==='completed').slice(-5).map((step,index)=><li key={index} className="flex gap-2 text-xs leading-5 text-slate-600"><Check size={13} className="mt-0.5 shrink-0 text-teal-600"/>{step.label}</li>)}</ul></Box>{result.answer_structure?.note&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-[11px] leading-5 text-amber-900">{result.answer_structure.note}</p>}</div>:<EmptyState icon={<Lightbulb/>} title="No business answer yet" text="Ask a question to receive a plain-language answer supported by the data."/>;
  if(tab==='sql')return sqlSteps.length?<div><SectionTitle title="Executed SQL" text="Read-only queries used for this answer."/>{sqlSteps.map((step,index)=><pre key={index} className="mt-3 overflow-auto rounded-lg bg-slate-900 p-4 text-[11px] leading-5 text-slate-200">{step.result.query}</pre>)}</div>:<EmptyState icon={<TerminalSquare/>} title="No SQL for this answer" text="SQL appears here when the analysis uses a database query."/>;
  return result?<div><SectionTitle title="Analysis activity" text="A factual record of the work completed. Internal reasoning is not shown."/><div className="mt-4 space-y-1">{(result.steps?.length?result.steps:result.plan).map((step:any,index:number)=><div key={`${step.tool}-${index}`} className="flex gap-3 rounded-lg px-2 py-3 hover:bg-white"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full ${step.status==='failed'?'bg-red-100 text-red-600':'bg-emerald-100 text-emerald-700'}`}>{step.status==='failed'?<X size={11}/>:<Check size={11}/>}</span><div><div className="text-xs font-medium text-slate-700">{step.label}</div>{step.duration_ms!=null&&<div className="mt-1 text-[10px] text-slate-400">Completed in {step.duration_ms<1000?`${Math.round(step.duration_ms)} ms`:`${(step.duration_ms/1000).toFixed(1)} sec`}</div>}{step.error&&<div className="mt-1 text-[10px] text-red-600">{step.error}</div>}</div></div>)}</div></div>:<EmptyState icon={<Activity/>} title="No activity yet" text="Completed analysis steps will appear here."/>;
}

function AnswerView({result}:{result:AnalystResult}){const answer=result.answer_structure;if(!answer)return <div className="whitespace-pre-wrap text-[14px] leading-7 text-slate-700">{result.answer||'The analysis is waiting for your review.'}</div>;return <div className="space-y-4"><div className="text-[16px] font-semibold leading-7 text-slate-900">{answer.headline}</div>{answer.metrics?.length>0&&<div className="grid grid-cols-2 gap-2">{answer.metrics.map(metric=><div key={metric.label} className="rounded-lg border border-slate-200 bg-slate-50 p-3"><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{metric.label}</div><div className="mt-1 text-lg font-semibold text-slate-900">{metric.value}</div></div>)}</div>}{answer.sections?.filter(section=>section.items.length).map(section=><section key={section.title} className="rounded-lg border border-slate-200 bg-white p-4"><h3 className="text-xs font-semibold uppercase tracking-wide text-teal-700">{section.title}</h3><ul className="mt-2 space-y-2">{section.items.map((item,index)=><li key={index} className="flex gap-2 text-[13px] leading-6 text-slate-700"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-500"/>{item}</li>)}</ul></section>)}{answer.note&&<p className="border-l-2 border-amber-300 pl-3 text-xs leading-5 text-slate-600">{answer.note}</p>}</div>}

function Approval({result,pending,decide}:{result:AnalystResult;pending:boolean;decide:(value:string)=>void}){const preview=result.pending_approval?.preview||{};const operations=preview.operations||preview.transformations||[];return <div className="mx-auto mb-6 max-w-3xl rounded-xl border border-amber-200 bg-amber-50 p-5"><div className="flex gap-3"><ShieldCheck className="shrink-0 text-amber-700" size={20}/><div><div className="text-sm font-semibold text-slate-900">Review proposed data changes</div><p className="mt-1 text-xs leading-5 text-slate-600">A new version will be created. The original dataset stays unchanged.</p><ul className="mt-3 space-y-1">{operations.map((item:any,index:number)=><li key={index} className="text-xs text-slate-700">• {words(item.operation||item.type||'data change')} {item.column?`on ${words(item.column)}`:''}</li>)}</ul><div className="mt-4 flex gap-2"><button disabled={pending} onClick={()=>decide('approve')} className="rounded-md bg-[#153c3f] px-3 py-2 text-xs font-semibold text-white">Apply to new version</button><button disabled={pending} onClick={()=>decide('reject')} className="rounded-md border border-slate-300 bg-white px-3 py-2 text-xs text-slate-700">Keep current data</button></div></div></div></div>}
function MiniStat({label,value}:{label:string;value:any}){return <div className="rounded-lg border border-slate-200 bg-white p-3"><div className="text-[10px] uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 text-lg font-semibold text-slate-900">{value}</div></div>}
function Box({title,children}:{title:string;children:any}){return <div className="rounded-lg border border-slate-200 bg-white p-4"><div className="mb-2 text-xs font-semibold text-slate-800">{title}</div>{children}</div>}
function SectionTitle({title,text}:{title:string;text:string}){return <div><h3 className="text-sm font-semibold text-slate-900">{title}</h3><p className="mt-1 text-[11px] leading-5 text-slate-500">{text}</p></div>}
function EmptyState({icon,title,text}:{icon:any;title:string;text:string}){return <div className="grid min-h-64 place-items-center text-center"><div><span className="mx-auto grid h-10 w-10 place-items-center rounded-lg bg-slate-100 text-slate-400 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div className="mt-3 text-sm font-semibold text-slate-700">{title}</div><div className="mx-auto mt-1 max-w-56 text-xs leading-5 text-slate-400">{text}</div></div></div>}
