import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link,useParams} from 'react-router-dom';
import Plot from 'react-plotly.js';
import {ArrowLeft,ArrowRight,BarChart3,CheckCircle2,Database,FileText,LayoutDashboard,Lightbulb,MessageSquareText,ShieldCheck,Trash2} from 'lucide-react';
import {api,Dataset} from '../api';
import {Badge,Empty,Page,Panel,Stat} from '../components/UI';
const fmt=(v:any)=>v==null?'—':typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):String(v);
const words=(v:string)=>v.replaceAll('_',' ');
const useCase=(v:string)=>({business_analysis:'Business questions',binary_classification:'Yes/no prediction',classification:'Group prediction',regression:'Number prediction',time_series:'Trends over time'}[v]||words(v));
const metricName=(v:string)=>({f1:'Balanced score',roc_auc:'Ranking quality',accuracy:'Correct answers',precision:'Positive answer reliability',recall:'Positive cases found',rmse:'Average prediction error',mae:'Typical prediction error',r2:'Variation explained'}[v]||words(v));

export function Overview(){
  const ds=useQuery({queryKey:['datasets'],queryFn:()=>api<Dataset[]>('/api/datasets')}); const ex=useQuery({queryKey:['experiments'],queryFn:()=>api<any[]>('/api/experiments')}); const sessions=useQuery({queryKey:['sessions'],queryFn:()=>api<any[]>('/api/analyst/sessions')});
  return <Page title="Good morning" description="Turn company data into answers your team can use.">
    <section className="grid grid-cols-[1.35fr_.65fr] gap-5"><div className="rounded-2xl bg-[#153c3f] p-8 text-white shadow-sm"><div className="text-xs font-semibold uppercase tracking-[.15em] text-[#8be3d5]">Your business copilot</div><h2 className="mt-4 max-w-xl text-3xl font-semibold leading-tight">Ask a question. Get a clear answer backed by your data.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/65">Understand customers, spot changes, check data quality, and build predictions without writing code.</p><Link to="/analyst" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-white px-5 py-3 text-sm font-semibold text-[#153c3f]">Ask your first question <ArrowRight size={16}/></Link></div><Panel title="How it works"><ol className="space-y-5">{[['1','Choose your data'],['2','Ask in everyday language'],['3','Review the answer and decide']].map(([n,t])=><li key={n} className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-teal-50 text-xs font-semibold text-teal-700">{n}</span><span className="text-sm text-slate-700">{t}</span></li>)}</ol></Panel></section>
    <div className="mt-6 grid grid-cols-3 gap-4"><Stat label="Connected data sources" value={ds.data?.length??'—'} note="Ready to explore"/><Stat label="Questions answered" value={sessions.data?.length??'—'} note="Saved for your team"/><Stat label="Predictions tested" value={ex.data?.length??'—'} note="Compared using real results"/></div>
    <div className="mt-6 grid grid-cols-[1.2fr_.8fr] gap-5"><Panel title="Your connected data"><div className="divide-y divide-slate-100">{ds.data?.slice(0,5).map(d=><div key={d.id} className="flex items-center gap-4 py-3 first:pt-0 last:pb-0"><div className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-slate-600"><Database size={17}/></div><div className="min-w-0 flex-1"><div className="text-sm font-medium text-slate-800">{d.display_name}</div><div className="mt-0.5 truncate text-xs text-slate-400">{d.description}</div></div><div className="text-xs text-slate-500">{fmt(d.rows)} records</div></div>)}</div></Panel><Panel title="Recent questions">{sessions.data?.slice(0,5).map(s=><Link to="/history" key={s.id} className="flex items-center justify-between border-b border-slate-100 py-3 last:border-0"><div><div className="text-sm text-slate-700">{s.title}</div><div className="mt-1 text-[11px] text-slate-400">{new Date(s.updated_at).toLocaleString()}</div></div><ArrowRight size={14} className="text-slate-300"/></Link>)}{!sessions.data?.length&&<Empty>Your answered questions will appear here.</Empty>}</Panel></div>
  </Page>
}

export function Datasets(){
  const {data}=useQuery({queryKey:['datasets'],queryFn:()=>api<Dataset[]>('/api/datasets')});
  return <Page title="Company data" description="The trusted data sources DataPilot can use to answer your questions." actions={<Link to="/analyst" className="rounded-lg bg-[#153c3f] px-4 py-2.5 text-sm font-semibold text-white">Ask about your data</Link>}><div className="grid gap-4">{data?.map(d=><Panel key={d.id}><div className="flex items-start gap-5"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-teal-50 text-teal-700"><Database size={20}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="font-semibold text-slate-900">{d.display_name}</h2><Badge tone="green">Ready</Badge></div><p className="mt-1 text-sm leading-6 text-slate-500">{d.description}</p><div className="mt-4 flex flex-wrap gap-2">{d.tasks.map(x=><Badge key={x}>{useCase(x)}</Badge>)}</div><div className="mt-4 text-xs text-slate-400">Source: {d.source} · {d.license}</div><Link to={`/analyst?dataset=${d.id}`} className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-teal-700 hover:text-teal-900">Ask about this data <ArrowRight size={14}/></Link></div><div className="grid shrink-0 grid-cols-2 gap-x-8 gap-y-3 text-right"><div><div className="text-xl font-semibold text-slate-900">{fmt(d.rows)}</div><div className="text-[11px] text-slate-400">records</div></div><div><div className="text-xl font-semibold text-slate-900">{d.columns}</div><div className="text-[11px] text-slate-400">fields</div></div><div className="col-span-2 text-xs text-slate-500">Main outcome: <strong className="font-medium text-slate-700">{d.targets.map(words).join(', ')||'Not set'}</strong></div></div></div></Panel>)}</div></Page>
}

export function Quality(){
  const [selected,setSelected]=useState(''); const ds=useQuery({queryKey:['datasets'],queryFn:()=>api<Dataset[]>('/api/datasets')}); const profile=useQuery({queryKey:['profile',selected],queryFn:()=>api<any>(`/api/datasets/${selected}/profile`),enabled:!!selected});
  return <Page title="Data health" description="Check whether your data is complete, consistent, and ready to use." actions={<select value={selected} onChange={e=>setSelected(e.target.value)} className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm outline-none"><option value="">Choose data to check</option>{ds.data?.map(d=><option key={d.id} value={d.id}>{d.display_name}</option>)}</select>}>{profile.isFetching?<Panel><Empty>Checking the data…</Empty></Panel>:profile.data?<><div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex gap-3"><CheckCircle2 className="text-emerald-700"/><div><div className="font-semibold text-emerald-900">{profile.data.issues.length?'Health check complete':'This data looks ready to use'}</div><div className="mt-1 text-sm text-emerald-800">{profile.data.issues.length?`We found ${profile.data.issues.length} items worth reviewing.`:'No major missing-data or repeated-row problems were found.'}</div></div></div></div><div className="grid grid-cols-4 gap-4"><Stat label="Records checked" value={fmt(profile.data.shape.rows)}/><Stat label="Information missing" value={`${profile.data.missing_pct}%`}/><Stat label="Repeated records" value={profile.data.duplicate_rows}/><Stat label="Items to review" value={profile.data.issues.length}/></div><Panel title="Information quality by field" className="mt-6"><table><thead><tr><th>Information field</th><th>Complete</th><th>Different values</th><th>What needs attention</th></tr></thead><tbody>{profile.data.columns.map((c:any)=><tr key={c.name}><td className="font-medium text-slate-800">{words(c.name)}</td><td>{(100-c.missing_pct).toFixed(1)}%</td><td>{fmt(c.unique)}</td><td>{c.constant?<Badge tone="red">Same value everywhere</Badge>:c.high_cardinality?<Badge tone="amber">Many different values</Badge>:c.potential_id?<Badge>Record identifier</Badge>:<span className="text-emerald-700">Looks good</span>}</td></tr>)}</tbody></table></Panel></>:<Panel><Empty>Choose a data source above to see whether it is ready for analysis.</Empty></Panel>}</Page>
}

export function Experiments(){
  const {data}=useQuery({queryKey:['experiments'],queryFn:()=>api<any[]>('/api/experiments')});
  return <Page title="Predictions" description="See the prediction approaches DataPilot tested and how well they worked." actions={<Link to="/analyst" className="rounded-lg bg-[#153c3f] px-4 py-2.5 text-sm font-semibold text-white">Create a prediction</Link>}><Panel><table><thead><tr><th>Approach</th><th>What it predicts</th><th>Type of answer</th><th>Results</th><th>Tested</th></tr></thead><tbody>{data?.map(x=><tr key={x.id}><td className="font-medium capitalize text-slate-900">{words(x.algorithm)}</td><td>{words(x.target)}</td><td>{x.task_type.includes('classification')?'A group or yes/no answer':'A number'}</td><td>{Object.entries(x.metrics).slice(0,2).map(([k,v]:any)=><div key={k} className="mb-1"><span className="text-slate-400">{metricName(k)}:</span> <strong className="font-medium text-slate-700">{['f1','roc_auc','accuracy','precision','recall','r2'].includes(k)?`${(Number(v)*100).toFixed(1)}%`:Number(v).toFixed(3)}</strong></div>)}</td><td>{new Date(x.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>{!data?.length&&<Empty>No predictions have been created yet. Ask DataPilot to predict an outcome.</Empty>}</Panel></Page>
}

export function History(){
  const {data}=useQuery({queryKey:['sessions'],queryFn:()=>api<any[]>('/api/analyst/sessions')});
  return <Page title="Past questions" description="Return to the business questions your team has explored."><div className="grid gap-3">{data?.map(s=><Panel key={s.id}><div className="flex items-center gap-4"><div className="grid h-10 w-10 place-items-center rounded-lg bg-slate-100 text-slate-500"><MessageSquareText size={18}/></div><div className="flex-1"><div className="font-medium text-slate-900">{s.title}</div><div className="mt-1 text-xs text-slate-400">Asked {new Date(s.updated_at).toLocaleString()}</div></div>{s.state?.target&&<Badge>Studied: {words(s.state.target)}</Badge>}{s.state?.model_experiments?.length>0&&<Badge tone="green">Prediction created</Badge>}</div></Panel>)}{!data?.length&&<Panel><Empty>Your completed questions will be saved here.</Empty></Panel>}</div></Page>
}

export function Memory(){
  const qc=useQueryClient(); const {data}=useQuery({queryKey:['memory'],queryFn:()=>api<any[]>('/api/memory')}); const del=useMutation({mutationFn:(id:string)=>api(`/api/memory/${id}`,{method:'DELETE'}),onSuccess:()=>qc.invalidateQueries({queryKey:['memory']})}); const clear=useMutation({mutationFn:()=>api('/api/memory',{method:'DELETE'}),onSuccess:()=>qc.invalidateQueries({queryKey:['memory']})});
  return <Page title="Saved insights" description="Useful findings DataPilot remembers for future questions." actions={<button onClick={()=>clear.mutate()} className="rounded-lg border border-red-200 bg-white px-3 py-2 text-xs text-red-600">Forget everything</button>}><div className="grid gap-3">{data?.map(x=><Panel key={x.id}><div className="flex items-start gap-4"><div className="grid h-10 w-10 place-items-center rounded-lg bg-amber-50 text-amber-700"><Lightbulb size={18}/></div><div className="min-w-0 flex-1"><div className="text-xs font-medium text-slate-400">{x.value?.query||'Saved finding'}</div><div className="mt-2 line-clamp-3 text-sm leading-6 text-slate-700">{x.value?.answer||x.value?.preference||'Context saved for a future question.'}</div></div><button aria-label="Forget this insight" onClick={()=>del.mutate(x.id)} className="rounded-lg p-2 text-slate-300 hover:bg-red-50 hover:text-red-500"><Trash2 size={16}/></button></div></Panel>)}{!data?.length&&<Panel><Empty>Important findings from your questions will appear here.</Empty></Panel>}</div></Page>
}

export function Visualizations(){
  const {data}=useQuery({queryKey:['visualizations'],queryFn:()=>api<any[]>('/api/visualizations')});
  return <Page title="Charts" description="Every chart created during analysis is saved here for review." actions={<Link to="/analyst" className="rounded-lg bg-[#153c3f] px-4 py-2.5 text-sm font-semibold text-white">Create a chart</Link>}><Panel><div className="overflow-x-auto"><table><thead><tr><th>Chart</th><th>Type</th><th>Uses</th><th>Created</th><th></th></tr></thead><tbody>{data?.map(v=><tr key={v.id}><td><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-teal-50 text-teal-700"><BarChart3 size={17}/></span><span className="font-medium text-slate-900">{v.title}</span></div></td><td className="capitalize">{words(v.specification?.chart_type||'chart')}</td><td>{[v.specification?.x,v.specification?.y].filter(Boolean).map(words).join(' and ')||'Computed analysis result'}</td><td>{new Date(v.created_at).toLocaleString()}</td><td className="text-right"><Link to={`/visualizations/${v.id}`} className="inline-flex items-center gap-1 rounded-md border border-slate-200 px-3 py-2 text-xs font-semibold text-teal-700 hover:border-teal-400 hover:bg-teal-50">View chart <ArrowRight size={13}/></Link></td></tr>)}</tbody></table></div>{!data?.length&&<Empty>Ask DataPilot to create a chart and it will be saved here.</Empty>}</Panel></Page>
}

export function VisualizationDetail(){
  const {id}=useParams(); const {data,isLoading,error}=useQuery({queryKey:['visualization',id],queryFn:()=>api<any>(`/api/visualizations/${id}`),enabled:!!id});
  if(isLoading)return <Panel><Empty>Opening the saved chart…</Empty></Panel>;
  if(error||!data)return <Panel><Empty>The saved chart could not be opened.</Empty></Panel>;
  const spec=data.specification||{};
  return <Page title={data.title} description={`Saved chart from ${data.dataset_name||'an analysis dataset'}.`} actions={<Link to="/visualizations" className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><ArrowLeft size={15}/>All charts</Link>}><div className="grid grid-cols-[1fr_300px] gap-5"><Panel><Plot data={data.figure.data} layout={{...data.figure.layout,paper_bgcolor:'transparent',plot_bgcolor:'transparent',autosize:true,margin:{...data.figure.layout?.margin,t:60}}} config={{displaylogo:false,responsive:true,toImageButtonOptions:{format:'png',filename:data.title}}} useResizeHandler style={{width:'100%',height:560}}/></Panel><div className="space-y-4"><Panel title="Chart details"><dl className="space-y-4 text-sm"><Detail label="Dataset" value={data.dataset_name||'—'}/><Detail label="Chart type" value={words(spec.chart_type||'chart')}/><Detail label="Horizontal axis" value={spec.x?words(spec.x):'Not used'}/><Detail label="Vertical axis" value={spec.y?words(spec.y):spec.aggregation||'Count'}/><Detail label="Grouping" value={spec.color?words(spec.color):'None'}/><Detail label="Created" value={new Date(data.created_at).toLocaleString()}/></dl></Panel><Panel title="How to use it"><p className="text-xs leading-6 text-slate-600">Hover over the chart to see exact values. Use the chart toolbar to zoom, reset the view, or download an image.</p></Panel></div></div></Page>
}

export function Dashboard(){
  const {data}=useQuery({queryKey:['visualizations'],queryFn:()=>api<any[]>('/api/visualizations')});
  const health=useQuery({queryKey:['health'],queryFn:()=>api<any>('/api/system/health')});
  return <Page title="Management dashboard" description="A shared view of the charts created from validated analysis." actions={<Link to="/analyst" className="rounded-lg bg-[#153c3f] px-4 py-2.5 text-sm font-semibold text-white">Add analysis</Link>}><div className="mb-5 grid grid-cols-3 gap-4"><Stat label="Saved charts" value={data?.length??'—'} note="Generated from real data"/><Stat label="Refresh status" value="Current" note="Using stored analysis results"/><Stat label="Data source" value={health.data?.storage||'Unavailable'} note={health.data?.database==='healthy'?'Connected locally':'Needs attention'}/></div><div className="grid grid-cols-2 gap-4">{data?.map(chart=><Panel key={chart.id}><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-teal-50 text-teal-700"><BarChart3 size={18}/></span><div><div className="font-semibold text-slate-900">{chart.title}</div><div className="mt-1 text-xs text-slate-400">Created {new Date(chart.created_at).toLocaleString()}</div><div className="mt-3 text-xs text-slate-500">Chart type: {words(chart.specification?.chart_type||'visual analysis')}</div></div></div></Panel>)}{!data?.length&&<div className="col-span-2"><Panel><Empty>Ask DataPilot to create charts, then they will appear on this dashboard.</Empty></Panel></div>}</div></Page>
}

export function Reports(){
  const {data}=useQuery({queryKey:['sessions'],queryFn:()=>api<any[]>('/api/analyst/sessions')});
  return <Page title="Analysis reports" description="Open a saved investigation and review the original question, answer, and completed steps." actions={<Link to="/analyst" className="rounded-lg bg-[#153c3f] px-4 py-2.5 text-sm font-semibold text-white">Start new analysis</Link>}><Panel><div className="overflow-x-auto"><table><thead><tr><th>Analysis</th><th>Last updated</th><th>Outcome</th><th></th></tr></thead><tbody>{data?.map(session=><tr key={session.id}><td><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-slate-600"><FileText size={17}/></span><span className="font-medium text-slate-900">{session.title}</span></div></td><td>{new Date(session.updated_at).toLocaleString()}</td><td>{session.state?.target?words(session.state.target):'Business analysis'}</td><td className="text-right"><Link to={`/reports/${session.id}`} className="inline-flex items-center gap-1 rounded-md border border-slate-200 px-3 py-2 text-xs font-semibold text-teal-700 hover:border-teal-400 hover:bg-teal-50">View analysis <ArrowRight size={13}/></Link></td></tr>)}</tbody></table></div>{!data?.length&&<Empty>Completed analyses will be available here as reusable reports.</Empty>}</Panel></Page>
}

export function ReportDetail(){
  const {id}=useParams(); const {data,isLoading,error}=useQuery({queryKey:['report',id],queryFn:()=>api<any>(`/api/analyst/sessions/${id}`),enabled:!!id});
  if(isLoading)return <Panel><Empty>Opening the saved analysis…</Empty></Panel>;
  if(error||!data)return <Panel><Empty>The saved analysis could not be opened.</Empty></Panel>;
  return <Page title={data.title} description="Saved analysis record" actions={<Link to="/reports" className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><ArrowLeft size={15}/>All reports</Link>}><div className="space-y-5">{data.runs?.map((run:any)=><Panel key={run.id}><div className="flex items-start justify-between gap-5"><div><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Question asked</div><h2 className="mt-2 text-lg font-semibold text-slate-900">{run.query}</h2></div><Badge tone={run.status==='completed'?'green':'amber'}>{words(run.status)}</Badge></div><div className="mt-5 border-t border-slate-100 pt-5"><div className="text-[10px] font-semibold uppercase tracking-wider text-teal-700">Business answer</div>{run.answer?<div className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-700">{run.answer}</div>:<div className="mt-3 text-sm text-slate-500">This older record does not contain a saved final answer. Its completed analysis steps are shown below.</div>}</div><div className="mt-5 rounded-lg bg-slate-50 p-4"><div className="text-xs font-semibold text-slate-700">Analysis completed</div><div className="mt-2 flex flex-wrap gap-2">{run.plan?.map((step:any,index:number)=><span key={index} className="rounded-full border border-slate-200 bg-white px-2.5 py-1 text-[10px] text-slate-600">{step.label}</span>)}</div></div><div className="mt-3 text-[10px] text-slate-400">Generated {new Date(run.created_at).toLocaleString()}</div></Panel>)}</div></Page>
}

export function Connections(){
  const health=useQuery({queryKey:['health'],queryFn:()=>api<any>('/api/system/health'),refetchInterval:15000}); const datasets=useQuery({queryKey:['datasets'],queryFn:()=>api<Dataset[]>('/api/datasets')});
  const connected=health.data?.database==='healthy';
  const recovery=health.data?.storage==='Local recovery database';
  return <Page title="Data connection" description="This page confirms where DataPilot reads and stores your data."><div className="mb-5 rounded-xl border border-blue-200 bg-blue-50 p-5"><div className="text-sm font-semibold text-blue-900">Why this connection is needed</div><p className="mt-1 text-sm leading-6 text-blue-800">DataPilot uses a database to read datasets, calculate answers, save charts, and keep analysis reports. The status below updates automatically every 15 seconds.</p>{recovery&&<p className="mt-2 text-sm leading-6 text-amber-800">Docker Desktop is unavailable. Public datasets are temporarily available from a separate local recovery database. Earlier PostgreSQL reports and cleaned versions will return when Docker starts again.</p>}</div><div className="grid grid-cols-[1fr_.7fr] gap-5"><Panel><div className="flex items-start gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><Database size={20}/></span><div className="flex-1"><div className="flex items-center gap-2"><div className="font-semibold text-slate-900">{health.data?.storage||'Database'}</div><Badge tone={connected?'green':'red'}>{health.isFetching?'Checking':connected?'Connected':'Unavailable'}</Badge></div><p className="mt-2 text-sm leading-6 text-slate-500">Stores the datasets, safe versions, analysis history, charts, and model experiments for this running session.</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-lg bg-slate-50 p-3"><div className="text-[10px] text-slate-400">Datasets available</div><div className="mt-1 text-lg font-semibold text-slate-900">{datasets.data?.length??'—'}</div></div><div className="rounded-lg bg-slate-50 p-3"><div className="text-[10px] text-slate-400">Current status</div><div className="mt-1 text-sm font-semibold text-slate-900">{connected?'Ready for analysis':'Database needs attention'}</div></div></div></div></div></Panel><Panel title="Add your data"><div className="grid place-items-center py-5 text-center"><LayoutDashboard className="text-teal-700"/><div className="mt-3 text-sm font-semibold text-slate-800">Upload a CSV</div><p className="mt-1 max-w-xs text-xs leading-5 text-slate-500">Use the workspace upload button. DataPilot stores the file as a new raw dataset without changing existing data.</p><Link to="/analyst" className="mt-4 rounded-lg bg-[#153c3f] px-4 py-2 text-xs font-semibold text-white">Open workspace</Link></div></Panel></div></Page>
}

function Detail({label,value}:{label:string;value:string}){return <div><dt className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{label}</dt><dd className="mt-1 capitalize text-slate-700">{value}</dd></div>}
